### ISSUE TITLE
Add data for Cardinal Health (Fortune16)

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#35]
## Feature description
Add a file with data for [Cardinal Health](https://fortune.com/company/cardinal-health/fortune500/)

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company.  If information for a field cannot be found, leave it blank or delete that line.

**Comment by hilbug** [comment]
@kelseyhuse30  I'll take this one too

**Comment by hilbug** [comment]
@kelseyhuse30 Not finding any formal company statement for BLM or the like. I did find a blurb they posted on LinkedIn, so I am going to add that as the statement: https://www.linkedin.com/posts/cardinal-health_i-cant-breathe-george-floyds-death-activity-6672273993170530304-r9vw/

Since LinkedIn doesn't have an exact date (just says 5 months ago), I am picking 5/29 based on this timing: https://en.wikipedia.org/wiki/George_Floyd_protests_in_Columbus,_Ohio

Found a few articles - but I don't classify them as statements since they are not direct from the company:

- https://www.bizjournals.com/columbus/news/2020/06/12/cardinal-health-hr-chief-on-developing-inclusive-l.html?b=1591988483%5E21688677
- https://www.bizjournals.com/columbus/news/2020/06/08/cardinal-health-ceo.html?b=1591635096%5E21686064
- https://www.columbusceo.com/business/20200827/why-mike-kaufmann-does-difficult-work-of-chasing-real-change
- https://www.alpha-sense.com/insights/blm-pride

**Comment by kelseyhuse30** [comment]
@hilbug thank you!! I think you nailed the posted date because I googled "Cardinal Health George Floyd" and found this facebook post, which was May 29: https://www.facebook.com/1204723189643417/posts/i-cant-breathegeorge-floyds-death-should-never-have-happened-inhumanity-against-/2986310264818025/

I love the extra articles you found.  I'm thinking of how I can add these in to the data.  You may have inspired me to add another field for "related resources" 🤔 🤔

**Comment by hilbug** [comment]
Didn't think of checking Facebook! I'll keep that in mind. :)
